/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaybookIndexRouteImport } from './routes/playbook.index'
import { Route as PlaybookSlugRouteImport } from './routes/playbook.$slug'

const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/playbook/',
  path: '/playbook/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookSlugRoute = PlaybookSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlaybookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbook': typeof PlaybookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/glossary' | '/playbook/$slug' | '/playbook/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/glossary' | '/playbook/$slug' | '/playbook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/glossary'
    | '/playbook/$slug'
    | '/playbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GlossaryRoute: typeof GlossaryRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/playbook'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/$slug': {
      id: '/playbook/$slug'
      path: '/$slug'
      fullPath: '/playbook/$slug'
      preLoaderRoute: typeof PlaybookSlugRouteImport
      parentRoute: typeof PlaybookRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GlossaryRoute: GlossaryRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
